sign_off_message=("That's all, have a great day!")
print("Hi! My name is Vida and I am twelve years old(almost 13)")
input()
print("I live in Seattle,Wa but I was born in New York City")
input()
print("I'm in eighth grade at SAAS!")
input()
print("I love to dance and do gymnastics!")
input()
print("I do tumbling and artistic gymnastics.")
print("In tumbling you do only floor but you do tramp too.")
print("Artistic gymnastics is the normal Olympics style gymnastics!")
input()
print("I have two dogs: Hazel and Bear")
input()
print("Hazel is a 7 year old german shepard-basset hound")
print("Bear is a 8 month old german shepard-great pyrenees but he's already 90 pounds!")
input()
print("Now I want to learn about you!")
their_name=input("What's your name?")
print(f"Hi {their_name},nice to meet you!")
their_color=input("What's your favorite color?")
print(f"{their_color}? Wow that's a good choice! Mine is sunset orange pinkish!")
input() 
print(sign_off_message)