print("why did the man bring his watch to the bank?")
input()
print("because he wanted to save time!!!!")
input()
print("why can't you trust atoms?")
input() 
print("because they make up everything!!!")
input()
print("why did the golfer need in pants?")
input()
print("because he got a hole in one!")