print("Welcome to the beach!")
print("pick a character!")
name=input("Do you want piper or turtle or seagull or crab ")
print(f"Hi {name}")
input()
print("pick a color!")
color=input("Brown, blue, green, pink, red, or teal")
print(f"I love the color {color}!")
friend=input("write the name of your favorite animal")
print(f"{friend}? AWWW thats so cute!!!")
pal=input("okay now write a name" )
input()
print(f"your best friend is {pal} the {friend}")
input()
print(f"one day you and {pal} the  {friend} were taking a stroll on the beach just along the edge of the water")
input()
print(f"then all of a sudden {pal} stops")
input()
problem=input("What happened?(pick one)stubbed my toe- got sand in my eyes- feel sick")
input()
print(f"I {problem} exclaims {pal}!")
print("OH NO!!!! you shriek")
solution=input("What can I do to help?")
if solution == "nothing":
    print("okay im sorry")
else: 
    print("okay!")
input()
print(f"After a bit you and {pal} started walking back to your house in the sand dunes.")
print("Your stomach starts growling")
print("what would you like to eat?")
food=input("Ramen, sushi, pasta, tofu, taco, watermelon, or smoothie")
input()
print("great choice!")
print(f"You and {pal} walk across the boardwalk to the {food} place. The sun is setting as the tide splashes across the sand.")

print("What a lovely day at the beach!!")
