print("Welcome to the beach!")
print("pick a character!")
name=input("Do you want piper or turtle or seagull or crab ")
print(f"Hi {name}")
input()
print("pick a color!")
color=input("Brown, blue, green, pink, red, or teal")
print(f"I love the color {color}!")
print("write the name of your favorite animal")